-- MySQL Script generated by MySQL Workbench
-- sáb 18 mar 2023 20:59:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `student_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `lastname` VARCHAR(100) NOT NULL,
  `birthday` DATE NOT NULL,
  `nationality` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Program`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Program` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Program` (
  `program_id` INT NOT NULL AUTO_INCREMENT,
  `sia_code` VARCHAR(30) NOT NULL,
  `education_level` VARCHAR(45) NOT NULL DEFAULT 'PREGRADO',
  `name` VARCHAR(45) NOT NULL,
  `mandatory_disciplinary_credits` INT NOT NULL,
  `mandatory_fundamental_credits` INT NOT NULL,
  `optional_disciplinary_credits` INT NOT NULL,
  `optional_fundamental_credits` INT NOT NULL,
  `free_choice_credits` VARCHAR(45) NOT NULL,
  `department` VARCHAR(45) NOT NULL,
  `faculty` VARCHAR(45) NOT NULL,
  `campus` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`program_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AcademicHistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AcademicHistory` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AcademicHistory` (
  `academic_history_id` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT NOT NULL,
  `program_id` INT NOT NULL,
  `sia_code` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`academic_history_id`),
  INDEX `student_id_idx` (`student_id` ASC) VISIBLE,
  INDEX `program_id_idx` (`program_id` ASC) VISIBLE,
  CONSTRAINT `student_id_Acad`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `program_id_Acad`
    FOREIGN KEY (`program_id`)
    REFERENCES `mydb`.`Program` (`program_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RegistrationDate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`RegistrationDate` ;

CREATE TABLE IF NOT EXISTS `mydb`.`RegistrationDate` (
  `registration_date_id` INT NOT NULL AUTO_INCREMENT,
  `academic_history_id` INT NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  PRIMARY KEY (`registration_date_id`),
  INDEX `academic_history_id_idx` (`academic_history_id` ASC) VISIBLE,
  CONSTRAINT `academic_history_id_reg`
    FOREIGN KEY (`academic_history_id`)
    REFERENCES `mydb`.`AcademicHistory` (`academic_history_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Course` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Course` (
  `course_id` INT NOT NULL AUTO_INCREMENT,
  `sia_code` VARCHAR(15) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `credits` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`course_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Typology`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Typology` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Typology` (
  `typology_id` INT NOT NULL AUTO_INCREMENT,
  `program_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `typology` VARCHAR(45) NOT NULL,
  INDEX `course_id_idx` (`course_id` ASC) VISIBLE,
  PRIMARY KEY (`typology_id`),
  CONSTRAINT `program_id_typology`
    FOREIGN KEY (`program_id`)
    REFERENCES `mydb`.`Program` (`program_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `course_id_typology`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`Course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Prerequisite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Prerequisite` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Prerequisite` (
  `prerequisite_id` INT NOT NULL AUTO_INCREMENT,
  `main_course_typology_id` INT NOT NULL,
  `pre_course_id` INT NOT NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (`prerequisite_id`),
  INDEX `main_course_id_idx` (`main_course_typology_id` ASC) VISIBLE,
  INDEX `pre_course_id_idx` (`pre_course_id` ASC) VISIBLE,
  CONSTRAINT `typology_id_prerequisite`
    FOREIGN KEY (`main_course_typology_id`)
    REFERENCES `mydb`.`Typology` (`typology_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `course_id_prerequisite`
    FOREIGN KEY (`pre_course_id`)
    REFERENCES `mydb`.`Course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Professor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `professor_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `birthday` DATE NOT NULL,
  `nationality` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `email` VARCHAR(100) NOT NULL,
  `status` VARCHAR(45) NULL DEFAULT 'ACTIVE',
  `entrance_date` DATE NOT NULL,
  `retirement_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`professor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Group` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Group` (
  `group_id` INT NOT NULL AUTO_INCREMENT,
  `group_number` INT NOT NULL,
  `semester` VARCHAR(45) NOT NULL,
  `seats` INT NOT NULL,
  `professor_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`group_id`),
  INDEX `course_id_idx` (`course_id` ASC) VISIBLE,
  INDEX `professor_id_idx` (`professor_id` ASC) VISIBLE,
  CONSTRAINT `course_id_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`Course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `professor_id`
    FOREIGN KEY (`professor_id`)
    REFERENCES `mydb`.`Professor` (`professor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HistoryCourse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`HistoryCourse` ;

CREATE TABLE IF NOT EXISTS `mydb`.`HistoryCourse` (
  `history_course_id` INT NOT NULL AUTO_INCREMENT,
  `academic_history_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  `grade` FLOAT NOT NULL,
  `typology` VARCHAR(45) NULL,
  PRIMARY KEY (`history_course_id`),
  INDEX `group_id_idx` (`group_id` ASC) VISIBLE,
  INDEX `academic_history_id_idx` (`academic_history_id` ASC) VISIBLE,
  CONSTRAINT `academic_history_id_history`
    FOREIGN KEY (`academic_history_id`)
    REFERENCES `mydb`.`AcademicHistory` (`academic_history_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `mydb`.`Group` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Schedule` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Schedule` (
  `schedule_id` INT NOT NULL AUTO_INCREMENT,
  `group_id` INT NOT NULL,
  `classroom_name` VARCHAR(45) NULL,
  `classroom_code` VARCHAR(45) NOT NULL,
  `weekday` INT NOT NULL,
  `start_hour` VARCHAR(10) NOT NULL,
  `end_hour` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`schedule_id`),
  INDEX `group_id_idx` (`group_id` ASC) VISIBLE,
  CONSTRAINT `group_id_schedule`
    FOREIGN KEY (`group_id`)
    REFERENCES `mydb`.`Group` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
