-- MySQL Script generated by MySQL Workbench
-- dom 19 mar 2023 23:05:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GradesWarehouse
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `GradesWarehouse` ;

-- -----------------------------------------------------
-- Schema GradesWarehouse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GradesWarehouse` ;
USE `GradesWarehouse` ;

-- -----------------------------------------------------
-- Table `GradesWarehouse`.`Date`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GradesWarehouse`.`Date` ;

CREATE TABLE IF NOT EXISTS `GradesWarehouse`.`Date` (
  `date_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `year` INT NOT NULL,
  `semester` INT NOT NULL,
  `quarter` INT NOT NULL,
  `bimester` INT NOT NULL,
  `month` INT NOT NULL,
  `month_name` VARCHAR(45) NOT NULL,
  `week` INT NOT NULL,
  `weekday` INT NOT NULL,
  PRIMARY KEY (`date_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GradesWarehouse`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GradesWarehouse`.`Student` ;

CREATE TABLE IF NOT EXISTS `GradesWarehouse`.`Student` (
  `student_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `birthdate` VARCHAR(45) NOT NULL,
  `nationality` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GradesWarehouse`.`Program`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GradesWarehouse`.`Program` ;

CREATE TABLE IF NOT EXISTS `GradesWarehouse`.`Program` (
  `program_id` INT NOT NULL,
  `sia_code` VARCHAR(45) NOT NULL,
  `education_level` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `mandatory_disciplinary_credits` INT NOT NULL,
  `mandatory_fundamental_credits` INT NOT NULL,
  `optional_disciplinary_credits` INT NOT NULL,
  `optional_fundamental_credits` INT NOT NULL,
  `free_choice_credits` INT NOT NULL,
  `department` VARCHAR(45) NOT NULL,
  `faculty` VARCHAR(45) NOT NULL,
  `campus` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`program_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GradesWarehouse`.`Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GradesWarehouse`.`Professor` ;

CREATE TABLE IF NOT EXISTS `GradesWarehouse`.`Professor` (
  `professor_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `birthdate` VARCHAR(45) NOT NULL,
  `nationality` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NULL,
  `entrance_date` DATE NULL,
  `retirement_date` DATE NULL,
  PRIMARY KEY (`professor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GradesWarehouse`.`CourseGroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GradesWarehouse`.`CourseGroup` ;

CREATE TABLE IF NOT EXISTS `GradesWarehouse`.`CourseGroup` (
  `course_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  `sia_code` VARCHAR(45) NULL,
  `group_number` INT NULL,
  `name` VARCHAR(45) NULL,
  `credits` INT NULL,
  `seats` INT NULL,
  `hourly_intensity` INT NULL,
  `hourly_intensity_am` INT NULL,
  `hourly_intensity_pm` INT NULL,
  INDEX `idx_group_id` (`group_id` ASC) VISIBLE,
  PRIMARY KEY (`course_id`, `group_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GradesWarehouse`.`AcademicHistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GradesWarehouse`.`AcademicHistory` ;

CREATE TABLE IF NOT EXISTS `GradesWarehouse`.`AcademicHistory` (
  `academic_history_id` INT NOT NULL,
  `program_id` INT NOT NULL,
  `sia_code` VARCHAR(45) NOT NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`academic_history_id`, `program_id`),
  INDEX `fk_program_id_idx` (`program_id` ASC) VISIBLE,
  CONSTRAINT `fk_program_id_to_academic_history_id`
    FOREIGN KEY (`program_id`)
    REFERENCES `GradesWarehouse`.`Program` (`program_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GradesWarehouse`.`CurriculumFact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GradesWarehouse`.`CurriculumFact` ;

CREATE TABLE IF NOT EXISTS `GradesWarehouse`.`CurriculumFact` (
  `program_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  `count_prerequisites` INT NOT NULL,
  INDEX `fk_course_id_idx` (`course_id` ASC) VISIBLE,
  PRIMARY KEY (`program_id`, `course_id`, `group_id`),
  INDEX `fk_group_id_to_CurriculumFact_idx` (`group_id` ASC) VISIBLE,
  CONSTRAINT `fk_program_id_to_CurriculumFact`
    FOREIGN KEY (`program_id`)
    REFERENCES `GradesWarehouse`.`Program` (`program_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_id_to_CurriculumFact`
    FOREIGN KEY (`course_id`)
    REFERENCES `GradesWarehouse`.`CourseGroup` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_id_to_CurriculumFact`
    FOREIGN KEY (`group_id`)
    REFERENCES `GradesWarehouse`.`CourseGroup` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GradesWarehouse`.`CourseFact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GradesWarehouse`.`CourseFact` ;

CREATE TABLE IF NOT EXISTS `GradesWarehouse`.`CourseFact` (
  `course_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  `program_id` INT NOT NULL,
  `professor_id` INT NOT NULL,
  `grade_sum` DECIMAL NOT NULL,
  `student_count` INT NOT NULL,
  `approved_count` INT NOT NULL,
  `failed_count` INT NOT NULL,
  INDEX `fk_group_id_idx` (`group_id` ASC) VISIBLE,
  INDEX `fk_program_id_idx` (`program_id` ASC) VISIBLE,
  INDEX `fk_professor_id_idx` (`professor_id` ASC) VISIBLE,
  PRIMARY KEY (`course_id`, `group_id`, `program_id`, `professor_id`),
  CONSTRAINT `fk_course_id_to_CourseFact`
    FOREIGN KEY (`course_id`)
    REFERENCES `GradesWarehouse`.`CourseGroup` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_id_to_CourseFact`
    FOREIGN KEY (`group_id`)
    REFERENCES `GradesWarehouse`.`CourseGroup` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_program_id_to_CourseFact`
    FOREIGN KEY (`program_id`)
    REFERENCES `GradesWarehouse`.`Program` (`program_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professor_id_to_CourseFact`
    FOREIGN KEY (`professor_id`)
    REFERENCES `GradesWarehouse`.`Professor` (`professor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GradesWarehouse`.`GradesFact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GradesWarehouse`.`GradesFact` ;

CREATE TABLE IF NOT EXISTS `GradesWarehouse`.`GradesFact` (
  `grade_date_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  `professor_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  `program_id` INT NOT NULL,
  `academic_history_id` INT NOT NULL,
  `history_course_id` INT NOT NULL,
  `grade` DECIMAL NOT NULL,
  `approved` INT NOT NULL,
  INDEX `fk_course_id_idx` (`course_id` ASC) VISIBLE,
  INDEX `fk_group_id_idx` (`group_id` ASC) VISIBLE,
  INDEX `fk_professor_id_idx` (`professor_id` ASC) VISIBLE,
  INDEX `fk_student_id_idx` (`student_id` ASC) VISIBLE,
  INDEX `fk_program_id_idx` (`program_id` ASC) VISIBLE,
  INDEX `fk_academic_history_id_idx` (`academic_history_id` ASC) VISIBLE,
  PRIMARY KEY (`grade_date_id`, `course_id`, `group_id`, `professor_id`, `student_id`, `program_id`, `academic_history_id`, `history_course_id`),
  CONSTRAINT `fk_grade_date_id_to_GradesFact`
    FOREIGN KEY (`grade_date_id`)
    REFERENCES `GradesWarehouse`.`Date` (`date_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_id_to_GradesFact`
    FOREIGN KEY (`course_id`)
    REFERENCES `GradesWarehouse`.`CourseGroup` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_id_to_GradesFact`
    FOREIGN KEY (`group_id`)
    REFERENCES `GradesWarehouse`.`CourseGroup` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professor_id_to_GradesFact`
    FOREIGN KEY (`professor_id`)
    REFERENCES `GradesWarehouse`.`Professor` (`professor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_id_to_GradesFact`
    FOREIGN KEY (`student_id`)
    REFERENCES `GradesWarehouse`.`Student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_program_id_to_GradesFact`
    FOREIGN KEY (`program_id`)
    REFERENCES `GradesWarehouse`.`Program` (`program_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_academic_history_id_to_GradesFact`
    FOREIGN KEY (`academic_history_id`)
    REFERENCES `GradesWarehouse`.`AcademicHistory` (`academic_history_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
